### ISSUE TITLE
Enable USB automount 

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#20]
#### Describe the bug
- raspbian lite(on which susibian is based) doesn't automount USB drives.
- Mounting is required in order for the media-daemon to work for USB audio playback 

#### Expected behaviour
- Automount USB drives

**Comment by hongquan** [comment]
In old SUSI Linux codebase, as far as I remember, the "media daemon" already takes care of mounting USB device. If it doesn't work now, it is just something broken and has to fix, not to introduce more software to the stack (and making mess).

If you really need automount for removable disks, not matter whether "media daemon" exists, use [udisks](https://wiki.archlinux.org/index.php/Udisks), instead of _usbmount_.

**Comment by norbusan** [comment]
Indeed ... the meda_daemo is broken ... I will repair it. The path have changed and so it doesn't start... wait a moment.

**Comment by norbusan** [comment]
Ok, I pushed some changes. I need to leave now but tonight I will verify whether it works or not.

@alok760 I have reverted the usbmount changes. Indeed, we don't need double work. Please let us try to fix the media_daemon, it does already skill generation if it works properly.

@hongquan Thanks for pointing me at this! TIll now I haven't looked into the media daemon, will fix that soon.

**Comment by norbusan** [comment]
Please see https://github.com/norbusan/susi_installer/tree/media-daemon-rework where I rework the partition reading and mounting in auto_skill.py

**Comment by hongquan** [comment]
Look OK.

**Comment by norbusan** [comment]
Send PR which should close this issue. What still needs to be improved is the auto-skill generation
